// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zvorydksgvuyenqrzmcl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inp2b3J5ZGtzZ3Z1eWVucXJ6bWNsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0ODkzNjEsImV4cCI6MjA1ODA2NTM2MX0.mB-lU5cJa5GmdsSLO3y5jCr-txw50lbLynKuaD3kLx4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);